### ISSUE TITLE
some error occur

### ISSUE THREAD

**Issue by kscMaster** [gdutxiaoxu/BaseLibrary#1]
ERROR: Unable to resolve dependency for ':QQBroswerDemo@debug/compileClasspath': Could not resolve project :submodules:BaseLibrary.
这个依赖怎么回事，为什么lib包裹在了module里，studio 3.3.2不识别

**Comment by babyofish** [comment]
me too

**Comment by gdutxiaoxu** [comment]
执行以下命令
```
git submodule init, git submodule update
```
